export const DATA = [
  "I am talking with Tom.",
  "I am talking with Tom. He is nice.",
  "I came to the conclusion that I had been deceived.",
  "Are you for or against my plan?",
  "I am not acquainted with him.",
  "There is an exception to every rule.",
  "It rained all day yesterday.",
  "He's friendly with everyone in his class.",
  "She advised him not to borrow money from his friends.",
  "She got him to eat his vegetables.",
  "I took Highway 58.",
  "This is the only alternative.",
  "No, I'm full.",
  "Yes, but I am. I've gained 10 pounds in the last two months. Look at my stomach.",
  "What color?",
  "He is still very much alive.",
  "He left after he had lunch.",
  "I want to be a pilot in the future.",
  "She gave him the brush off.",
  "What are you trying to do?",
  "He had an accident at work.",
  "Do you know how to get to the Marriott Hotel?",
  "I opened the door and saw two boys standing side by side.",
  "He was listening to music.",
  "Every time they talk, they argue.",
  "Have you been told when to come?",
  "I accompanied her on the piano.",
  "It's my favorite food.",
  "I let the cat out of the house.",
  "He has plenty of money in the bank.",
];
